nome = input('Qual é o seu nome? ')
print('Olá,', nome+'! Prazer em conhecê-lo(a).\n')
print('Eu gostaria que você me informasse alguns dados, ok? Vamos lá!\n')
print('Escreva o dia, mês e ano do seu nascimento:\n')
dia = input('Dia: ')
mes = input('Mês: ')
ano = input('Ano: ')
print('A data do seu aniversário é dia', dia,'de', mes,'de', ano,'('+dia+'/'+mes+'/'+ano+').')
